# This is a basic workflow to help you get started with Actions

name: Login Token

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch

  ## uncomment below lines to run automatically 

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  k6_local_test:
    name: Login Token load test run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Run k6 cloud test
      #   uses: k6io/action@v0.1
      #   with:
      #     filename: tests/graphQL_API_Test/create_Login_Token.js
      #     cloud: true
      #     token: ${{ secrets.K6_CLOUD_API_TOKEN }}

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/graphQL_API_Test/create_Login_Token.js

      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: filename
          
      - name: PR Comment from File
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: filename
          
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
